### PR TITLE
Python 2 to Python 3

### PR DESCRIPTION
**Pull request by mdinger**
Seems to work correctly. Slowing down the connection rate fixed the network dropping. I was wondering about unused imports so I ran a lint and removed all the extra ones.

I'm not sure what you think about `get_time` vs `GetTime` but it seems more consistent. The rest is just nitpicks pointed out by the linter.

### CODE REVIEW

**Comment by tdaede** [comment]
This looks good. I had to make this one change, but it seems to behave correctly now:
https://github.com/tdaede/rd_tool/commit/66bc74716b54b9fb9802f719a24a46af64a53ff6

**Comment by mdinger** [comment]
Cool. I pulled your commit into this PR so feel free to merge if you like. Probably should do awcy at the same time.

Without that extra commit, what's it do? Mix up Daala and Daala Test instances (and maybe more if they exist)?

**Comment by tdaede** [comment]
Yeah, without the commit it would use both instances.

I won't update the versions running on arewecompressedyet.com until next week because I'll be traveling over the weekend and I hear it's a bad idea to make big changes on a Friday afternoon.

**Comment by mdinger** [comment]
Do you mean you won't update rd_tool on arewecompressedyet or you won't merge https://github.com/tdaede/awcy/pull/48 until next week? I ask because awcy probably won't work correctly calling rd_tool with python2 now.

**Comment by tdaede** [comment]
I will merge the awcy issue today, but I won't do a synchronized update
of the two repos on the arewecompressedeyet.com VM until next week.

My sets.json change also requires some synchronized changes so I'll
include them both at once.

**Comment by mdinger** [comment]
Okay cool.

**Pull request merged**
