### PR TITLE
SVT-AV1: run single-threaded by default

### PR DESCRIPTION
**Pull request by kylophone**
This updates svt-av1 to always run single threaded.

### CODE REVIEW

**Comment by kylophone** [comment]
@tdaede Thanks, let me know when you add the missing svt-avt directory to all the servers and I'll try another run.

**Comment by tdaede** [comment]
I just tried one, the actual binaries are failing now. looking at it.

**Comment by kylophone** [comment]
@tdaede, wondering if you have any update on this?

**Comment by kylophone** [comment]
The command line seems to work locally for me.

```
./Bin/Release/SvtAv1EncApp -i ~/Desktop/nyan.yuv -enc-mode 0 -lp 1 -q 24 -o out.yuv -b out.ivf -w 480 -h 304 -intra-period 100
```

**Comment by tdaede** [comment]
@kylophone got it working on beta.arewecompressedyet.com now. Turned out to be library path issues, easy fix.

**Comment by kylophone** [comment]
> @kylophone got it working on beta.arewecompressedyet.com now. Turned out to be library path issues, easy fix.

Ah, great. Thanks!

**Pull request merged**
